"""empty message

Revision ID: a9c8a7552bda
Revises: 0aee70ac8bff
Create Date: 2019-12-11 09:27:26.972477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c8a7552bda'
down_revision = '0aee70ac8bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expense_name', sa.String(length=40), nullable=False),
    sa.Column('expense_cost', sa.Float(), nullable=False),
    sa.Column('expense_necessity', sa.String(length=15), nullable=False),
    sa.Column('expense_category', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
